---
sidebar: sidebar 
permalink: oracle/aws-ora-fsx-ec2-migration.html 
summary: 本節詳細介紹了將 Oracle 資料庫從本機遷移到 AWS EC2 執行個體和 FSx 儲存時需要考慮的因素。 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= 資料庫從本地遷移到公有雲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
無論如何，資料庫遷移都是一項具有挑戰性的任務。將 Oracle 資料庫從本機遷移到雲端也不例外。

以下部分提供了使用 AWS EC2 運算和 FSx 儲存平台將 Oracle 資料庫遷移到 AWS 公有雲時需要考慮的關鍵因素。



== ONTAP儲存可在本地使用

如果內部部署 Oracle 資料庫位於ONTAP儲存陣列上，則可以使用 AWS FSx ONTAP儲存內建的NetApp SnapMirror技術更輕鬆地設定資料庫遷移的複製。可以使用NetApp BlueXP控制台來協調遷移過程。

. 建構與本機執行個體相符的目標計算 EC2 執行個體。
. 從 FSx 控制台提供匹配的、大小相等的資料庫磁碟區。
. 將 FSx 資料庫磁碟區掛載到 EC2 執行個體。
. 設定本機資料庫磁碟區與目標 FSx 資料庫磁碟區之間的SnapMirror複製。初始同步可能需要一些時間來移動主要來源數據，但任何後續增量更新都會快得多。
. 切換時，關閉主應用程式以停止所有交易。從 Oracle sqlplus CLI 介面執行 Oracle 線上日誌切換並允許SnapMirror同步將最後的存檔日誌推送到目標磁碟區。
. 分解鏡像卷，在目標上執行 Oracle 恢復，並啟動資料庫進行服務。
. 將應用程式指向雲端中的 Oracle 資料庫。


以下影片示範如何使用NetApp BlueXP控制台和SnapMirror複製將 Oracle 資料庫從本機遷移到 AWS FSx/EC2。

.將本機 Oracle 資料庫遷移到 AWS
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto]


== ONTAP儲存在本地不可用

如果內部部署 Oracle 資料庫託管在ONTAP以外的第三方儲存上，則資料庫遷移將基於 Oracle 資料庫備份副本的還原。您必須在切換之前播放存檔日誌以使其變為最新。

AWS S3 可作為資料庫移動和遷移的暫存儲存區域。請參閱此方法的以下進階步驟：

. 預置一個與本地執行個體相當的新的符合 EC2 執行個體。
. 從 FSx 儲存配置相等的資料庫磁碟區並將磁碟區掛載到 EC2 執行個體。
. 建立磁碟級 Oracle 備份副本。
. 將備份副本移至 AWS S3 儲存體。
. 重新建立 Oracle 控製檔案並透過從 S3 儲存中提取資料和存檔日誌來還原和還原資料庫。
. 將目標 Oracle 資料庫與本機來源資料庫同步。
. 切換時，關閉應用程式和來源 Oracle 資料庫。複製最後幾個存檔日誌並將其套用到目標 Oracle 資料庫以保持最新。
. 啟動目標資料庫以供使用者存取。
. 將應用程式重新導向到目標資料庫以完成切換。




== 使用 PDB 遷移將本機 Oracle 資料庫遷移到 AWS FSx/EC2，並實現最高可用性

這種遷移方法最適合已在 PDB/CDB 多租用戶模型中部署的 Oracle 資料庫，且ONTAP儲存在本機上不可用。  PDB 重定位方法利用 Oracle PDB 熱克隆技術在來源 CDB 和目標 CDB 之間移動 PDB，同時最大限度地減少服務中斷。

首先，在 AWS FSx/EC2 中建立具有足夠儲存空間的 CDB，以託管要從本地遷移的 PDB。可以一次重新定位多個本地 PDB。

. 如果本機資料庫部署在單一實例中，而不是多租用戶 PDB/CDB 模型中，請依照link:azure-ora-nfile-migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb["將單一實例非 CDB 轉換為多租戶 CDB 中的 PDB"^]將單一實例轉換為多租用戶 PDB/CDB。然後按照下一步將轉換後的 PDB 遷移到 AWS FSx/EC2 中的 CDB。
. 如果本機資料庫已部署在多租用戶 PDB/CDB 模型中，請依照link:azure-ora-nfile-migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation["使用 PDB 遷移將本機 Oracle 資料庫遷移到雲端"^]執行遷移。


以下影片示範如何使用 PDB 重定位將 Oracle 資料庫 (PDB) 遷移到 FSx/EC2 以實現最大可用性。

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796["將本機 Oracle PDB 遷移到具有最大可用性的 AWS CDB"^]


NOTE: 雖然步驟 1 和 2 中的說明是在 Azure 公有雲的背景下說明的，但這些流程無需任何變更即可適用於 AWS 雲端。

NetApp解決方案自動化團隊提供了一個遷移工具包，可以促進 Oracle 資料庫從本地遷移到 AWS 雲端。使用下列指令下載用於 PDB 重定位的 Oracle 資料庫遷移工具包。

[source, cli]
----
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
----