---
sidebar: sidebar 
permalink: dbops/hybrid-dbops-sc-prereq-cloud.html 
summary: 在安裝 Cloud Manager 連接器和Cloud Volumes ONTAP並設定SnapMirror之前，我們必須為我們的雲端環境進行一些準備。本頁介紹了部署Cloud Volumes ONTAP時需要完成的工作以及注意事項。 
keywords: prerequisites, aws, azure, gcp, cloud central, cloud volumes ontap 
---
= 公有雲的先決條件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在安裝 Cloud Manager 連接器和Cloud Volumes ONTAP並設定SnapMirror之前，我們必須為我們的雲端環境進行一些準備。本頁介紹了部署Cloud Volumes ONTAP時需要完成的工作以及注意事項。



== Cloud Manager 和Cloud Volumes ONTAP部署前提清單

* NetApp Cloud Central 登入
* 透過 Web 瀏覽器存取多個端點的網絡
* 連接器的網路位置
* 雲端提供者權限
* 個人服務網絡


有關入門所需內容的更多信息，請訪問我們的 https://docs.netapp.com/us-en/occm/reference_checklist_cm.html["雲端文檔"^]。



== 注意事項



=== 1.什麼是 Cloud Manager 連接器？

大多數情況下，Cloud Central 帳戶管理員必須在您的雲端或本機網路中部署連接器。此連接器使 Cloud Manager 能夠管理公有雲環境中的資源和流程。

有關連接器的更多信息，請訪問我們的 https://docs.netapp.com/us-en/occm/concept_connectors.html["雲端文檔"^]。



=== 2.Cloud Volumes ONTAP 的大小與架構

部署Cloud Volumes ONTAP時，您可以選擇預先定義套件或建立自己的設定。儘管其中的許多值可以在以後無中斷地進行更改，但在部署之前需要根據要在雲端中部署的工作負載做出一些關鍵決策。

每個雲端供應商都有不同的部署選項，幾乎每個工作負載都有其獨特的屬性。  NetApp擁有 https://bluexp.netapp.com/calculator-hub["TCO計算機"^]它可以幫助根據容量和性能正確確定部署規模，但它是圍繞一些值得考慮的基本概念構建的：

* 所需容量
* 雲端虛擬機的網路能力
* 雲端儲存的效能特點


關鍵是要規劃一個不僅能滿足當前容量和性能要求，還能考慮未來成長的配置。這通常被稱為容量餘裕和效能餘裕。

如果您想了解更多信息，請閱讀有關正確規劃的文檔 https://docs.netapp.com/us-en/occm/task_planning_your_config.html["AWS"^]， https://docs.netapp.com/us-en/occm/task_planning_your_config_azure.html["Azure"^] ， 和 https://docs.netapp.com/us-en/occm/task_planning_your_config_gcp.html["地理控制協議"^]。



=== 3.單節點還是高可用性？

在所有雲端中，都可以選擇在單一節點或具有兩個節點的叢集高可用性對中部署 CVO。根據使用情況，您可能想要部署單一節點以節省成本或部署 HA 對以提供進一步的可用性和冗餘。

對於 DR 用例或為開發和測試啟動臨時存儲，單節點很常見，因為突然的區域或基礎設施中斷的影響較低。但是，對於任何生產用例，當資料僅位於單一位置時，或當資料集必須具有更多冗餘和可用性時，建議使用高可用性。

有關每個雲端版本的高可用性架構的更多信息，請訪問 https://docs.netapp.com/us-en/occm/concept_ha.html["AWS"^]， https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Azure"^]和 https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html["地理控制協議"^]。
