---
sidebar: sidebar 
permalink: automation/marketing-overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 本頁介紹在NetApp ONTAP儲存上部署 Oracle19c 的自動化方法。 
---
= 解決方案概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本頁介紹在NetApp ONTAP儲存上部署 Oracle19c 的自動化方法。



== 在 NFS 上自動部署 Oracle19c for ONTAP

組織正在實現其環境自動化，以提高效率、加速部署並減少人工工作量。 Ansible 等組態管理工具正被用來簡化企業資料庫操作。在此解決方案中，我們示範如何使用 Ansible 自動設定和設定具有NetApp ONTAP的 Oracle 19c。透過讓儲存管理員、系統管理員和 DBA 能夠一致、快速地部署新儲存、配置資料庫伺服器和安裝 Oracle 19c 軟體，您可以獲得以下好處：

* 消除設計複雜性和人為錯誤，並實施可重複的一致部署和最佳實踐
* 減少儲存配置、資料庫主機配置和 Oracle 安裝的時間
* 提高資料庫管理員、系統和儲存管理員的工作效率
* 輕鬆實現儲存和資料庫的擴展


NetApp為客戶提供經過驗證的 Ansible 模組和角色，以加速 Oracle 資料庫環境的部署、設定和生命週期管理。此解決方案提供了說明和 Ansible 劇本程式碼，以協助您：

* 為 Oracle 資料庫建立和配置ONTAP NFS 存儲
* 在 RedHat Enterprise Linux 7/8 或 Oracle Linux 7/8 上安裝 Oracle 19c
* 在ONTAP NFS 儲存上配置 Oracle 19c


欲了解更多詳細資訊或開始，請觀看下面的概述影片。



=== AWX/塔式部署

第 1 部分：入門、需求、自動化詳細資訊和初始 AWX/Tower 配置

.AWX 部署
video::d844a9c3-4eb3-4512-bf21-b01200f09f66[panopto]
第 2 部分：變數和運行劇本

.AWX 劇本運行
video::6da1b960-e1c9-4950-b750-b01200f0bdfa[panopto]


=== CLI部署

第 1 部分：入門、需求、自動化詳細資訊和 Ansible 控制主機設置

.CLI部署
video::373e7f2a-c101-4292-a3e4-b01200f0d078[panopto]
第 2 部分：變數和運行劇本

.CLI Playbook 運行
video::d58ebdb0-8bac-4ef9-b4d1-b01200f95047[panopto]